### PR TITLE
PLCT-Roadmap-2023.en.md: add English translation

### PR DESCRIPTION
**Pull request by MingcongBai**

### CODE REVIEW

**Review by lazyparser — APPROVED** [review]
Thanks

**Comment by JoannaWu84** [comment]
Hi! Here some modification suggestions, for reference only.

line:5  At the same time, we are pleased to announce that the Institute of Software, Chinese Academy of Sciences has established a new RUYISDK project in 2023, which aims to ...

line 21: Developers who have purchased almost any RISC-V development board or module will be able to obtain hardware datasheets, firmware/software updates, debugging support, etc., through the RUYISDK system. 

line 93: over 100 interns trained

**Comment by MingcongBai** [comment]
@JoannaWu84 Suggestions taken and updated translation. Thank you!

cc @lazyparser

**Comment by lazyparser** [comment]
Thanks

**Pull request merged**
